version: '3'
                          
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      - MONGO_URL=${MONGO_URL}

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork: {}
