# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 10s
  # scrape_protocols:
  #   - OpenMetricsText1.0.0
  #   - OpenMetricsText0.0.1
  #   - PrometheusText0.0.4
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# alerting:
#   alertmanagers:
#     - follow_redirects: true
#       enable_http2: true
#       scheme: http
#       timeout: 10s
#       api_version: v2
#       static_configs:
#         - targets: []  

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.s
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "vestimeteo"
    # honor_timestamps: true
    # track_timestamps_staleness: false
    # scrape_interval: 15s
    # scrape_timeout: 10s
    # scrape_protocols:
    #   - OpenMetricsText1.0.0
    #   - OpenMetricsText0.0.1
    #   - PrometheusText0.0.4
    # metrics_path: /metrics
    # scheme: http
    # enable_compression: true
    # follow_redirects: true
    # enable_http2: true

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["backend:8000"]  
        # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  